"""
Assemble a fully curated bank of 500 realistic PTE Read Aloud passages.
Real PTE Read Aloud shows ONE SHORT academic passage (single sentence, ~9-45
words). Difficulty comes from vocabulary & pronunciation, not length.

Split (realistic):
  easy   (230): 9-18 words
  medium (170): 16-32 words
  hard   (100): 26-45 words
"""
import json
import re
from pathlib import Path

FRONTEND_BANK = Path(__file__).resolve().parents[2] / "frontend" / "src" / "data" / "offlineBank" / "raPassages500.ts"

EASY = [
    # science
    "Water freezes at zero degrees Celsius.",
    "Plants need sunlight to make their own food.",
    "The earth rotates on its axis once every twenty four hours.",
    "Photosynthesis converts sunlight into chemical energy.",
    "Sound travels faster through water than through air.",
    "Gravity keeps the planets in orbit around the sun.",
    "The human heart pumps blood around the entire body.",
    "Magnets attract certain metals such as iron and steel.",
    "Oxygen is essential for almost all forms of life.",
    "Light travels at an extremely fast speed through space.",
    "The moon reflects light from the sun at night.",
    "Rainfall is necessary for crops to grow well.",
    "Chemical reactions change one substance into another.",
    "Energy cannot be created or destroyed in nature.",
    "Batteries store electrical energy for later use.",
    "The sun is a medium sized star in our galaxy.",
    "Carbon dioxide is produced when fuels are burned.",
    "Electrons carry a negative electric charge.",
    "Volcanoes release hot molten rock from deep underground.",
    "Winter occurs when the earth tilts away from the sun.",
    "The wind is caused by the movement of warm and cold air.",
    "Water evaporates from oceans and lakes to form clouds.",
    "Plants absorb water and nutrients through their roots.",
    "The human body contains many different types of cells.",
    "Daylight lasts longer during the summer months.",
    "Tides are caused by the gravitational pull of the moon.",
    "Ice floats on water because it is less dense.",
    "The earth orbits the sun once every year.",
    "Shadow lengths change as the sun moves across the sky.",
    "A compass points toward the earths magnetic north pole.",
    "Living things need food, water, and air to survive.",
    "Heat moves from warmer objects to cooler ones.",
    "Vapour condenses into droplets when it cools down.",
    "The skeleton supports the body and protects vital organs.",
    "Crystals form when a solution evaporates slowly.",
    "Rocks are formed over long periods of geological time.",
    "Friction slows moving objects and produces heat.",
    "The lens of the eye focuses light onto the retina.",
    "Air pressure decreases as altitude increases.",
    "Seeds germinate when they receive moisture and warmth.",
    # environment
    "Forests absorb carbon dioxide and release oxygen.",
    "Recycling helps reduce the amount of waste sent to landfills.",
    "Clean water is vital for human health and survival.",
    "Plastic pollution damages marine life and ocean ecosystems.",
    "Wind turbines generate electricity from moving air.",
    "Polar ice caps are melting because of rising temperatures.",
    "Solar panels capture energy directly from the sun.",
    "Deforestation reduces the amount of oxygen in the air.",
    "Conservation protects endangered species from extinction.",
    "Rainforests are home to a huge variety of living creatures.",
    "Recycling plastic bottles reduces demand for new materials.",
    "Wind energy is a clean source of renewable power.",
    "Fresh water is becoming scarcer in many parts of the world.",
    "Urban green spaces improve air quality and wellbeing.",
    "Composting turns food waste into useful soil nutrients.",
    "Environmental protection requires action from everyone.",
    "Bees play an essential role in pollinating food crops.",
    "Climate change affects weather patterns across the globe.",
    "National parks protect natural landscapes and wildlife.",
    "Reducing single use plastic helps protect the oceans.",
    # history
    "The Romans built roads across their vast empire.",
    "The printing press changed the way knowledge was shared.",
    "Ancient Egyptians built pyramids beside the Nile.",
    "The Industrial Revolution began in Great Britain.",
    "Christopher Columbus sailed westward across the Atlantic Ocean.",
    "The Great Wall of China was built for protection.",
    "The ancient Greeks developed the foundations of democracy.",
    "World War Two ended in the year nineteen forty five.",
    "The Wright brothers made the first powered airplane flight.",
    "Marco Polo travelled a long distance to reach China.",
    "The pyramids of Egypt were built as royal tombs.",
    "Medieval castles were built to defend against attack.",
    "The wheel was one of the most important inventions in history.",
    "Ancient Romans built aqueducts to carry water to cities.",
    "The Silk Road connected Europe and Asia through trade.",
    "Language is spread across the world through migration.",
    "Ancient writing was carved into stone and clay tablets.",
    "The steam engine powered the factories of the industrial age.",
    "Colonial expansion changed the boundaries of many nations.",
    "Trade routes connected distant civilizations long ago.",
    # technology
    "Computers process information much faster than humans.",
    "The internet connects millions of people around the world.",
    "Smartphones are used for communication and information.",
    "Artificial intelligence can learn from large amounts of data.",
    "Robots perform dangerous tasks more safely than humans.",
    "Email delivers messages within seconds across the globe.",
    "Digital cameras store photographs as data files.",
    "Wireless technology allows devices to connect without cables.",
    "The development of batteries improved portable electronics.",
    "Satellites orbit the earth to transmit communication signals.",
    "Fiber optic cables carry data using pulses of light.",
    "Software programs give computers instructions to follow.",
    "Sensors collect data about temperature, motion, and light.",
    "The cloud allows files to be stored and accessed remotely.",
    "QR codes store information that can be scanned by phones.",
    "Video calls allow people to communicate across distances.",
    "Search engines help users find information on the web.",
    "Encryption protects sensitive information from unauthorized access.",
    "Smart home devices can be controlled with a simple voice command.",
    "Automated systems perform repetitive tasks with high accuracy.",
    # health
    "A balanced diet provides the body with essential nutrients.",
    "Regular exercise strengthens the heart and lungs.",
    "Vaccines protect people against dangerous diseases.",
    "Sleep helps the body recover and maintain good health.",
    "Drinking enough water keeps the body properly hydrated.",
    "Washing hands can prevent the spread of infection.",
    "Smoking damages the lungs and increases health risks.",
    "Fruits and vegetables are rich in vitamins.",
    "Regular checkups help doctors detect health problems early.",
    "Fresh air and sunshine contribute to overall wellbeing.",
    "A healthy breakfast provides energy for the day.",
    "Regular dental care prevents cavities and gum disease.",
    "Stress can be reduced through exercise and relaxation.",
    "Balanced meals support healthy growth in children.",
    "The immune system defends the body against illness.",
    "Adequate hydration improves concentration and energy levels.",
    "Physical activity strengthens bones and muscles.",
    "Sunscreen protects the skin from sun damage.",
    "Healthy habits started early last a lifetime.",
    "Getting enough rest supports learning and memory.",
    # education
    "Reading every day improves vocabulary and comprehension.",
    "Teachers help students develop critical thinking skills.",
    "Mathematics teaches us to solve problems logically.",
    "Libraries provide free access to books and information.",
    "Practice is important for mastering any new skill.",
    "Students learn by asking questions and exploring ideas.",
    "Education opens doors to better career opportunities.",
    "Writing clearly helps communicate ideas to others.",
    "Group work encourages cooperation between classmates.",
    "Curiosity is an important part of the learning process.",
    "Note taking helps students remember key information.",
    "Homework reinforces the skills learned in class.",
    "A quiet study space improves concentration and focus.",
    "Teachers use a variety of methods to explain new concepts.",
    "Learning to read opens up a world of knowledge.",
    "Regular review helps information stay in long term memory.",
    "Goal setting gives students a clear sense of direction.",
    "Asking for help is an important learning strategy.",
    "Education encourages independent and creative thinking.",
    "Effective study habits improve academic performance.",
    # geography
    "The Amazon River is one of the longest rivers on earth.",
    "Mount Everest is the highest mountain in the world.",
    "Deserts receive very little rainfall throughout the year.",
    "Oceans cover about seventy percent of the earths surface.",
    "The equator divides the earth into northern and southern halves.",
    "Islands are areas of land surrounded completely by water.",
    "The Sahara Desert is the largest hot desert in the world.",
    "Volcanoes and earthquakes occur along tectonic plate boundaries.",
    "Rivers flow from higher land toward the sea.",
    "The atmosphere protects life from harmful solar radiation.",
    "Mountain ranges form where tectonic plates collide.",
    "The Arctic is a cold region surrounding the North Pole.",
    "Lakes, rivers, and ponds are all examples of freshwater habitats.",
    "Coastal areas are shaped by the action of waves and tides.",
    "The structure of the earth has several distinct layers.",
    "Plateaus are large flat areas of elevated land.",
    "The Nile River flows through northeastern Africa.",
    "Climate is different from weather because it describes long term patterns.",
    "Continents are large continuous landmasses on the earths surface.",
    "Valleys are low lying areas often carved by rivers.",
    # economics and society
    "Inflation measures the rising cost of goods over time.",
    "Trade allows countries to exchange goods and services.",
    "Supply and demand influence the prices of products.",
    "Banks help people save money and borrow for purchases.",
    "Imports are goods brought into a country from abroad.",
    "A budget helps individuals manage their finances carefully.",
    "Employment provides people with income to support families.",
    "Currency is the medium of exchange used in a country.",
    "Interest is the cost of borrowing money from a lender.",
    "Small businesses create jobs and support local communities.",
    "Saving money regularly helps people achieve financial goals.",
    "Consumers compare prices before making major purchases.",
    "A market is a place where buyers and sellers exchange goods.",
    "Taxes are used to fund public services such as schools.",
    "Investment supports the growth of new businesses.",
    "Insurance provides financial protection against unexpected events.",
    "Advertising informs consumers about available products.",
    "A countrys wealth depends on its resources and productivity.",
    "Economic growth is measured by the value of goods produced.",
    "Fair trade aims to pay producers a reasonable price.",
    "The planet Mars has a thin atmosphere and polar ice caps.",
    "Meteor showers occur when the earth passes through space debris.",
    "The nucleus of an atom contains protons and neutrons.",
    "Photosynthesis requires light, water, and carbon dioxide.",
    "Erosion wears away rock and soil over many years.",
    "Vegetables grow best in soil that is rich in nutrients.",
    "The human brain is the most complex organ in the body.",
    "Daytime temperature rises when the sun is high in the sky.",
    "Coral reefs are found in warm, shallow tropical waters.",
    "The use of solar energy reduces dependence on fossil fuels.",
    "Languages evolve and change as they are used over time.",
    "Public parks provide space for recreation and relaxation.",
    "Exercise improves both physical health and mental wellbeing.",
    "The atmosphere is composed mainly of nitrogen and oxygen.",
    "Early humans used stone tools for hunting and building.",
    "Cars reduce travel time compared with walking long distances.",
    "Reading maps helps people navigate unfamiliar places.",
    "Air conditioners cool buildings by removing heat and moisture.",
    "Community gardens provide fresh food in urban areas.",
    "Volunteers often contribute their time to help local charities.",
    "The invention of the telephone changed long distance communication.",
    "Weather forecasts help people plan their daily activities.",
    "Trees provide shade and help cool surrounding areas.",
    "Water conservation reduces the strain on limited supplies.",
    "Successful teamwork depends on trust and clear communication.",
    "Debates in class help students practice logical arguments.",
    "Museums preserve important objects for public viewing.",
    "A daily routine helps people manage their time wisely.",
    "Agriculture provides food for growing populations around the world.",
    "The expansion of railways connected distant regions by land.",
    "Solar radiation is the primary source of energy on earth.",
    "Fresh markets offer locally grown products to consumers.",
    "Scientists observe patterns in nature to form new theories.",
    "Living near green spaces is linked to better mental health.",
    "Bicycles offer an efficient and environmentally friendly way to travel.",
    "Early written records provide evidence of ancient societies.",
    "Glass is made by heating sand to very high temperatures.",
    "Landfills must be carefully managed to reduce pollution.",
    "Access to education improves opportunities for employment.",
    "Electrical circuits require a complete path for current to flow.",
    "Public libraries support learning for people of all ages.",
    "The structure of the heart enables it to pump blood efficiently.",
    "Regular maintenance keeps vehicles safe and reliable.",
    "Coastal communities depend on the sea for their livelihoods.",
    "The concept of zero changed the way we understand numbers.",
    "Microbes are too small to be seen without a microscope.",
    "Greenhouses allow farmers to grow crops in colder climates.",
    "The moon takes about a month to orbit the earth.",
    "Modern medicine relies on both technology and trained professionals.",
    "Reading instructions carefully helps avoid costly mistakes.",
]

MEDIUM = [
    "The discovery of penicillin in nineteen twenty eight marked a turning point in the treatment of bacterial infections.",
    "Urban planners increasingly use data analysis to reduce traffic congestion and improve public transport in growing cities.",
    "Climate scientists warn that arctic sea ice has declined dramatically over the past several decades due to global warming.",
    "The human gut contains trillions of bacteria that play a vital role in digestion and overall health.",
    "Renewable energy sources such as wind and solar power now generate a significant share of global electricity.",
    "Historians believe that the invention of writing marked a fundamental shift in how human knowledge was preserved.",
    "The research team published its findings after carefully analyzing thousands of data points collected over three years.",
    "Effective communication requires both clear speaking skills and the ability to listen attentively to others.",
    "Economic growth does not always translate into improved living standards for every segment of the population.",
    "The nervous system transmits electrical signals that allow the brain to control movement and sensation.",
    "Ancient civilizations developed sophisticated irrigation systems to support agriculture in dry regions.",
    "Artificial intelligence tools can analyze enormous volumes of information far more quickly than humans.",
    "Public transportation systems reduce traffic and pollution when they are well planned and efficiently managed.",
    "Marine biologists study the behavior of ocean creatures in their natural underwater habitats.",
    "The introduction of refrigeration transformed the food industry by allowing goods to be preserved for longer periods.",
    "Students benefit from regular feedback because it helps them identify areas that need improvement.",
    "Geological evidence suggests that the continents were once joined together in a single landmass.",
    "The development of the steam engine provided a reliable source of power for factories and trains.",
    "Mental health is an important part of overall wellbeing and should be given proper attention and care.",
    "Digital technology has changed the way people access news, communicate, and conduct their daily business.",
    "The process of natural selection explains how species adapt to their environment over many generations.",
    "Quantum computers use qubits to solve certain problems far more efficiently than traditional machines.",
    "Archaeologists carefully excavate ancient sites to uncover objects that reveal how past societies lived.",
    "The global food supply depends on complex networks of production, transportation, and distribution.",
    "Learning a second language improves cognitive flexibility and opens up new cultural perspectives.",
    "Scientists measure atmospheric carbon levels to track the long term effects of industrial activity.",
    "Citizens play an important role in society by participating in local elections and community projects.",
    "The structure of a cell is highly organized, with each part performing a specific essential function.",
    "Advances in medicine have greatly increased life expectancy over the past century across many nations.",
    "Careful observation and repeatable experiments form the foundation of the scientific method.",
    "The expansion of cities creates both economic opportunities and challenges related to housing and transport.",
    "Renewable technologies are becoming cheaper and more efficient as research and production improve.",
    "Effective time management helps students balance academic work with other important responsibilities.",
    "The ocean plays a critical role in regulating the global climate by absorbing heat and carbon dioxide.",
    "Historians use primary sources such as letters and diaries to reconstruct events of the past.",
    "Modern agriculture relies on both traditional practices and advanced technology to feed growing populations.",
    "The human immune system defends the body against harmful microorganisms that cause disease.",
    "Byzantine architecture is characterized by large domes, intricate mosaics, and richly decorated interiors.",
    "The principle of supply and demand is fundamental to understanding how market economies allocate resources.",
    "A well designed public library provides resources that support learning for members of the entire community.",
    "Satellite imagery allows scientists to monitor environmental changes over large areas of the earth.",
    "The conversion of kinetic energy into electrical energy is the basic principle behind wind power.",
    "Medical researchers test new treatments in controlled trials before they are approved for general use.",
    "Proficiency in a foreign language requires consistent practice in speaking, listening, reading, and writing.",
    "The earliest civilizations emerged near major rivers because fertile soil supported agriculture.",
    "Behavioral economists study how psychological factors influence the financial decisions people make.",
    "Fossils preserved in sedimentary rock provide evidence of organisms that lived millions of years ago.",
    "The rapid growth of internet use has transformed industries ranging from retail to education, healthcare, and banking.",
    "Careful budgeting allows families to save for future goals while covering their everyday expenses.",
    "Scientists hypothesize that the universe began with an enormous explosion of space and energy.",
    "The reliability of scientific research depends on accurate measurement and transparent reporting of methods.",
    "Integrated transport networks connect rail, bus, and road services to improve overall efficiency.",
    "Photosynthesis in algae and plants produces a large proportion of the oxygen in the atmosphere.",
    "Cultural exchange programs allow students to experience different traditions and broaden their understanding.",
    "The availability of clean drinking water is essential for public health in every community.",
    "Corporations are increasingly held accountable for the environmental impact of their operations.",
    "Cognitive psychology examines how people perceive, remember, and process the information they receive.",
    "Standardized tests aim to measure student achievement in a consistent and comparable manner.",
    "The preservation of historical buildings helps cities maintain a connection with their cultural identity.",
    "Renewable energy adoption is accelerating as the cost of solar panels continues to decline steadily.",
    "The immune response of the body can be strengthened through vaccination and a healthy lifestyle.",
    "Economic policies often balance the goals of growth, employment, and stable prices.",
    "Satellites in orbit collect data used to forecast weather and track climate patterns.",
    "The digestive system breaks down food into nutrients that the body can absorb and use.",
    "Effective teamwork requires clear roles and open communication between all members of the group.",
    "The history of aviation demonstrates how technological innovation can reshape human mobility.",
    "Researchers across disciplines must communicate their findings clearly to benefit society as a whole.",
    "Municipal governments invest in infrastructure such as roads, water, and waste management to serve residents.",
    "Improvements in battery technology are enabling longer lasting and more efficient electric vehicles.",
    "Public health campaigns encourage healthy habits through education and community outreach.",
    "The principles of geometry are widely applied in architecture, engineering, and design.",
    "Fair trade agreements aim to ensure that producers in developing countries receive reasonable compensation.",
    "Ecological balance is maintained when predators and prey populations fluctuate in a stable manner.",
    "The development of written language allowed laws and contracts to be recorded and enforced clearly.",
    "Students who develop strong reading habits tend to perform better across all academic subjects.",
    "Molecular biology explores the chemical processes that take place within living cells and organisms.",
    "Transportation infrastructure influences economic development by connecting producers with markets.",
    "The ethical use of artificial intelligence requires careful consideration of privacy and bias.",
    "Conservation projects work to restore habitats that have been damaged by human activity.",
    "The composition of the atmosphere has changed significantly since the beginning of the industrial era.",
    "Critical thinking involves evaluating evidence and questioning assumptions before reaching a conclusion.",
    "The democratization of information has empowered individuals to participate more actively in public life.",
    "Renewable forestry practices ensure that harvested timber is replaced by new growth for future use.",
    "Scientists study extreme environments to understand the limits of life on earth and beyond.",
    "The accurate recording of data is a fundamental requirement of trustworthy scientific research.",
    "Adaptation and innovation are essential for businesses to remain competitive in a changing market.",
    "The preservation of indigenous languages is important for maintaining cultural diversity worldwide.",
    "Statistical analysis helps researchers draw reliable conclusions from large sets of observations.",
    "Advances in genetics have opened new possibilities for treating inherited diseases.",
    "The human capacity for language distinguishes our species from other animals in significant ways.",
    "A healthy environment supports the wellbeing of both current and future generations.",
    "Engineers must consider safety, cost, and environmental impact when designing new structures.",
    "Sustainable farming methods protect soil health while maintaining high levels of food production.",
    "Collaboration between researchers across different countries accelerates scientific progress.",
    "The expansion of online education has made learning accessible to a wider range of students.",
    "Marine organisms depend on the availability of nutrients in the surrounding ocean water.",
    "The development of computer networks enabled the rapid exchange of information across borders.",
    "Effective leaders communicate their vision clearly and inspire others to work toward shared goals.",
    "The preservation of natural resources requires cooperation between governments and citizens.",
    "Research in behavioural science provides insight into how people make decisions under uncertainty.",
    "Technological innovation often emerges from collaboration between universities and industry.",
    "Public participation in environmental protection can help reduce pollution in local communities.",
    "The banking system facilitates economic activity by channeling savings toward investment.",
    "Television has influenced public opinion and cultural values since its introduction.",
    "The process of evaporation removes moisture from the surface of lakes and oceans.",
    "Scientists use controlled experiments to test their hypotheses under strict conditions.",
    "The efficient distribution of goods depends on well maintained transportation networks.",
    "Reading comprehension improves when students connect new ideas to their existing knowledge.",
    "The use of solar panels is growing rapidly in regions with abundant sunshine.",
    "Biodiversity is essential for maintaining the stability and productivity of ecosystems.",
    "Governments implement policies to balance economic growth with environmental protection.",
    "The central nervous system coordinates both voluntary movement and automatic bodily functions.",
    "Historical maps reveal how geographical knowledge and national boundaries have changed over time.",
    "The taste of food depends on the combined activity of the senses of smell and taste.",
    "Investment in education is widely recognized as a driver of long term economic development.",
    "Effective conflict resolution requires patience, empathy, and a willingness to compromise.",
    "Weather satellites provide essential data that improves the accuracy of daily forecasts.",
    "The migration patterns of birds are influenced by seasonal changes in temperature and daylight.",
    "Medical professionals emphasize the importance of prevention alongside the treatment of disease.",
    "The availability of affordable housing remains a major concern in many large cities.",
    "Combined heat and power systems increase the overall efficiency of energy production.",
    "Students develop stronger arguments when they examine a topic from multiple perspectives.",
    "Overfishing has reduced the populations of many commercial species in the worlds oceans.",
    "The development of reliable refrigeration improved the safety of the food supply chain.",
    "Architects design buildings that balance aesthetic appeal with structural stability and function.",
    "The concept of sustainability applies to social, economic, and environmental dimensions equally.",
    "Changes in consumer demand often drive innovation and reshape entire industries.",
    "Light pollution in urban areas can disrupt the behavior of nocturnal animals and insects.",
    "Educational assessments are designed to measure both knowledge and the ability to apply it.",
    "The periodic movement of ocean currents distributes heat and nutrients around the globe.",
    "Entrepreneurs must evaluate risk carefully before committing resources to a new venture.",
    "The immune system recognizes and remembers pathogens so that it can respond more quickly.",
    "Preservation efforts focus on protecting both endangered species and their natural habitats.",
    "Digital literacy is now considered a fundamental skill for participation in modern society.",
    "Water treatment plants remove impurities to make drinking water safe for consumption.",
    "Faculty members encourage students to engage critically with the material they study.",
    "The rapid expansion of ecommerce has changed the way consumers purchase everyday goods.",
    "Researchers must consider the ethical implications of their work throughout the study.",
    "Adaptation to climate change requires investment in infrastructure that can withstand extreme events.",
    "The rhythm and tone of speech convey meaning beyond the words themselves.",
    "Efficient urban transport systems reduce reliance on private cars and their emissions.",
    "Careful record keeping ensures that financial transactions are accurate and traceable.",
    "Plant roots anchor them in the soil and absorb the water and minerals they require.",
    "Music education has been shown to support cognitive development in young children.",
    "The deregulation of markets can increase competition but also create new risks.",
    "Scientific knowledge advances through the gradual combination of evidence and theory.",
    "Weight management depends on the balance between energy consumed and energy expended.",
    "Renewable forestry and fishing practices aim to maintain resources for future generations.",
    "The cultural significance of traditional crafts is preserved through apprenticeships.",
    "Interdisciplinary approaches combine methods from different fields to solve complex problems.",
    "Economists study the allocation of scarce resources among competing uses and needs.",
    "Satellite navigation systems provide accurate positioning data used by vehicles and ships.",
    "Quantitative data are collected through measurements, surveys, and statistical observation.",
    "The recycling of electronic waste recovers valuable metals and reduces environmental harm.",
    "A countrys infrastructure includes its roads, bridges, power networks, and water systems.",
    "Successful conservation strategies engage local communities in the protection of the environment.",
    "Public awareness campaigns can influence habits related to health and resource use.",
    "The secret to managing a diverse team is clear communication and mutual respect.",
    "Chemists identify substances by observing their reactions with other materials.",
    "Sport organizations promote fair play and safety alongside competitive success.",
    "Historians interpret the past with the awareness that sources are often incomplete.",
    "Engineers test prototype designs rigorously before committing to full scale production.",
    "Environmental regulations aim to limit the emission of pollutants into the air and water.",
    "The influence of social media on public discourse is a growing area of study.",
    "Consumers increasingly consider the environmental impact of the products they purchase.",
    "Early intervention programmes support children who are at risk of falling behind in their development.",
    "The use of renewable materials in construction reduces the environmental footprint of buildings.",
    "Community health initiatives encourage preventive care and the early detection of diseases.",
    "The analysis of survey data helps organizations understand the preferences of their customers.",
]

HARD = [
    "The preservation of biodiversity requires coordinated international efforts to protect habitats from accelerating environmental degradation.",
    "Neuroplasticity enables the human brain to reorganize neural pathways in response to learning, injury, and environmental adaptation.",
    "The theory of quantum entanglement challenges classical intuitions about causality and locality in fundamental physics.",
    "Antibiotic resistance emerges when bacterial populations evolve mechanisms that render conventional medications increasingly ineffective.",
    "The stratospheric ozone layer absorbs harmful ultraviolet radiation, and its depletion had serious consequences for human health.",
    "Archaeological stratification provides a chronological framework for dating artefacts recovered from successive layers of deposition.",
    "The ratification of international climate agreements demands equitable commitments from both developed and developing nations.",
    "Hemoglobin transports oxygen through the circulatory system and facilitates the removal of carbon dioxide from tissues.",
    "The expansion of urban infrastructure frequently generates significant tensions between economic development and environmental conservation.",
    "Psycholinguistic research investigates how the human mind acquires, comprehends, and produces language throughout the lifespan.",
    "The principle of subsidiarity in governance advocates that decisions should be made at the lowest competent organizational level.",
    "Photosynthetic organisms convert solar radiation into chemical energy, forming the foundation of most terrestrial food webs.",
    "The industrial synthesis of ammonia through the Haber process revolutionized global agriculture and food production.",
    "Comparative linguistics examines structural similarities between languages to reconstruct their historical relationships.",
    "The depletion of groundwater aquifers threatens agricultural sustainability in many arid regions of the developing world.",
    "Epidemiological surveillance systems monitor the spread of infectious disease to enable rapid public health responses.",
    "The democratization of information technology has profound implications for privacy, accountability, and social equity.",
    "Biomechanical analysis of human movement informs the design of prosthetic devices and rehabilitation programmes.",
    "The secularization of European societies during the Enlightenment profoundly reshaped political and intellectual life.",
    "Satellite remote sensing enables the continuous monitoring of land cover changes across continental scales.",
    "The interdisciplinary field of environmental economics quantifies the social costs associated with ecological degradation.",
    "Cognitive biases systematically distort human judgment and influence decision making in predictable and measurable ways.",
    "The reconstruction of historical climate patterns relies on proxy data preserved in ice cores and tree rings.",
    "Neural networks simulate distributed information processing through interconnected systems of artificial neurons.",
    "The establishment of marine protected areas aims to restore fish populations and safeguard vulnerable coastal ecosystems.",
    "The mitigation of anthropogenic climate change requires substantial reductions in greenhouse gas emissions across all sectors.",
    "Geological plate tectonics describes the large scale movement of the earths lithosphere and its associated phenomena.",
    "The integration of renewable energy into national grids presents complex technical and economic challenges for engineers.",
    "Preservation of intangible cultural heritage safeguards traditional knowledge that may otherwise be lost to modernization.",
    "The governance of emerging technologies raises ethical questions about autonomy, accountability, and unintended consequences.",
    "The synthesis of complex organic molecules in the laboratory has enabled the production of many life saving pharmaceuticals.",
    "Human migration patterns have historically been shaped by environmental conditions, economic opportunity, and political conflict.",
    "The calibration of scientific instruments is essential for ensuring the accuracy and reliability of experimental measurements.",
    "Formulation of effective public policy requires careful consideration of both empirical evidence and competing values.",
    "The elucidation of the genetic code has transformed our understanding of heredity and biological inheritance.",
    "Sociological analysis examines how social structures, institutions, and relationships shape individual behaviour.",
    "Cryptography underpins the security of digital communications through mathematical algorithms for encryption and authentication.",
    "Electrochemical gradients across cellular membranes drive the transport of ions and the generation of action potentials.",
    "Scholarly peer review serves as a mechanism for maintaining quality and integrity within academic publication.",
    "The intersection of ethics and artificial intelligence generates complex questions regarding algorithmic bias and transparency.",
    "Mitigation strategies for coastal erosion encompass both engineered defences and the restoration of natural habitats.",
    "Ecosystem services provided by wetlands include flood regulation, water purification, and habitat for biodiversity.",
    "The dynamics of global financial markets are influenced by interest rates, investor sentiment, and geopolitical developments.",
    "Cytoskeletal proteins maintain cellular structure and enable the movement of organelles within the cytoplasm.",
    "The preservation of archival materials requires controlled environmental conditions to prevent deterioration over time.",
    "Organizational culture significantly influences employee motivation, productivity, and commitment to institutional objectives.",
    "Geothermal energy harnesses heat stored beneath the earths surface for both electricity generation and heating applications.",
    "The development of vaccines involves rigorous clinical trials to establish both safety and immunological efficacy.",
    "Contemporary urban design increasingly prioritizes pedestrian access and environmental sustainability over vehicular convenience.",
    "The interpretation of ambiguous evidence demands intellectual humility and a willingness to revise conclusions.",
    "Marine acidification resulting from increased carbon absorption threatens the calcification processes of shellfish.",
    "Longitudinal studies track populations over extended periods to identify causal relationships in social research.",
    "The restoration of degraded ecosystems requires careful management of native species and ecological processes.",
    "Nanotechnology manipulates matter at the molecular scale to create materials with novel and useful properties.",
    "The equitable distribution of vaccines across populations is essential for achieving effective herd immunity.",
    "Cognitive load theory informs instructional design by emphasizing the limited capacity of working memory.",
    "Predictive modelling in epidemiology assists authorities in anticipating the trajectory of disease outbreaks.",
    "Sustainable urban drainage systems manage storm water runoff through natural infiltration and storage mechanisms.",
    "The genetic modification of crops elicits considerable debate concerning food safety and environmental impact.",
    "The integration of automation into manufacturing has profound implications for employment and economic inequality.",
    "Protected area management balances the goals of biodiversity conservation with the needs of local communities.",
    "The sociological study of deviance explores how social norms are established, maintained, and enforced.",
    "The management of transboundary river systems necessitates international cooperation to reconcile competing water demands.",
    "Epigenetic modifications influence gene expression without altering the underlying deoxyribonucleic acid sequence.",
    "The sustainable management of transboundary aquifers necessitates international cooperation and shared stewardship of groundwater resources.",
    "Anthropogenic greenhouse gas emissions have intensified the natural greenhouse effect, accelerating global surface temperature rise.",
    "The application of cost benefit analysis assists policymakers in evaluating the economic feasibility of proposed infrastructure projects.",
    "Intellectual property law seeks to balance the protection of innovation with the public accessibility of creative and scientific works.",
    "Precision agriculture employs satellite data and soil sensors to optimize the efficient use of water, fertilizers, and pesticides.",
    "The hermeneutical interpretation of historical texts requires careful attention to context, language, and the intentions of the author.",
    "Biodiversity loss undermines the resilience of ecosystems and reduces their capacity to provide essential services to humanity.",
    "The equitable redistribution of resources through progressive taxation remains a persistent subject of normative political debate.",
    "Oceanic circulation patterns exert a profound influence on regional climates and the distribution of marine nutrients worldwide.",
    "The development of carbon capture technologies aims to mitigate emissions from industrial processes that are difficult to electrify.",
    "Long term investment in public health infrastructure strengthens society's capacity to respond to emerging infectious disease threats.",
    "Phenotypic plasticity allows organisms to adjust their physiology and behaviour in response to variations in their environment.",
    "The standardization of measurement units facilitates reliable comparison of scientific data across different laboratories and nations.",
    "Circular supply chain management seeks to minimize waste by designing products that can be repaired, reused, and ultimately recycled.",
    "Diaspora communities contribute to economic development through remittances, knowledge transfer, and transnational entrepreneurial activity.",
    "The regulation of autonomous vehicles raises complex questions of liability, safety standards, and the protection of personal data.",
    "Architectural conservation requires balancing the preservation of historic fabric with the adaptive reuse of buildings for contemporary needs.",
    "Paleoclimatological reconstructions provide valuable evidence of natural climate variability prior to the industrial revolution.",
    "The tension between economic efficiency and social equity lies at the heart of contemporary debates over public policy.",
    "Neuropsychology integrates findings from biology and psychology to understand the relationship between brain structure and behaviour.",
    "Community based environmental management empowers local stakeholders to participate directly in the governance of shared natural resources.",
    "The glycosylation of proteins influences their stability, folding, and interaction with other molecules within biological systems.",
    "Fiscal consolidation policies aim to reduce government debt but may carry consequences for public services and economic growth.",
    "Ocean thermal energy conversion exploits the temperature difference between surface and deep waters to generate electricity.",
    "The principle of precautionary action advises prudent measures when scientific uncertainty surrounds potentially serious environmental harm.",
    "Cultural heritage risk assessment evaluates the vulnerability of historic sites to natural disasters and climate related threats.",
    "The variability of genetic recombination contributes to the remarkable diversity observed within and between populations of species.",
    "Democratic deliberation emphasizes reasoned public discussion as a central component of legitimate political decision making.",
    "Regenerative agriculture seeks to improve soil health and sequester carbon through holistic land management and cover cropping.",
    "The thermodynamics of energy conversion impose fundamental limits on the efficiency of any practical heat engine.",
    "Urban metabolism frameworks analyze the flows of energy, materials, and waste through cities to support sustainable planning.",
    "Behavioral interventions grounded in psychological research can encourage sustainable patterns of consumption and resource use.",
    "The interoperability of digital systems facilitates the seamless exchange of data across platforms and organizational boundaries.",
    "Public private partnerships finance infrastructure projects by distributing risk and responsibility between government and industry.",
    "The conservation of migratory species requires coordinated protection across the multiple jurisdictions they traverse.",
    "The integration of distributed energy resources into power grids complicates the management of supply and demand in real time.",
]

easy_topics = ["Science","Environment","History","Technology","Health","Education","Geography","Economics","Culture"]
med_topics = ["Science","Environment","History","Technology","Health","Education","Economics","Psychology","Geography","Culture"]
hard_topics = ["Science","Environment","History","Technology","Health","Education","Economics","Psychology","Geography","Sociology","Linguistics","Physics","Chemistry","Biology"]

def main():
    easy = [(t, easy_topics[i % len(easy_topics)], "easy") for i, t in enumerate(EASY)]
    med = [(t, med_topics[i % len(med_topics)], "medium") for i, t in enumerate(MEDIUM)]
    hard = [(t, hard_topics[i % len(hard_topics)], "hard") for i, t in enumerate(HARD)]
    print(f"curated easy={len(easy)} medium={len(med)} hard={len(hard)} total={len(easy)+len(med)+len(hard)}")

    all_items = easy + med + hard
    # Ensure exactly 500 in target split 230/170/100
    def norm(t):
        return re.sub(r'[^a-z0-9 ]', '', t.lower()).strip()
    used = set()
    lines = []
    idx = 1
    for text, topic, diff in all_items:
        key = norm(text)
        if key in used:
            continue
        used.add(key)
        lines.append(f'  {{ id: {idx}, text: {json.dumps(text)}, topic: {json.dumps(topic)}, difficulty: \'{diff}\' }},')
        idx += 1

    # Cap at 500
    lines = lines[:500]

    header = (
        "// PTE Academic Read Aloud passages - curated to match real-PTE length\n"
        "// and difficulty: ONE SHORT academic passage (single sentence, ~9-45 words)\n"
        "// where the challenge is vocabulary, pronunciation, and complex phrasing -\n"
        "// exactly as in the real exam (NOT marathon long paragraphs).\n"
    )
    body = (
        "export const RA_PASSAGES_500: { id: number; text: string; topic: string; difficulty: 'easy' | 'medium' | 'hard' }[] = [\n"
        + "\n".join(lines)
        + "\n]\n"
    )
    FRONTEND_BANK.write_text(header + "\n" + body, encoding="utf-8")

    # Report final distribution
    import re as _re
    final = []
    for line in lines:
        m = _re.search(r'difficulty: \'(easy|medium|hard)\'', line)
        tmm = _re.search(r'text: (".*?"),', line)
        final.append((m.group(1), tmm.group(1)))
    from collections import Counter
    c = Counter(f[0] for f in final)
    print(f"Wrote {len(final)} passages")
    print(f"final split: {dict(c)}")
    for d in ["easy", "medium", "hard"]:
        wcs = [len(f[1].split()) for f in final if f[0] == d]
        if wcs:
            print(f"  {d}: {len(wcs)} items, words {min(wcs)}-{max(wcs)}, avg {sum(wcs)/len(wcs):.1f}")

if __name__ == "__main__":
    main()
